SELECT FIRST_NAME,LAST_NAME, COALESCE(
	--COALESCE(TELEFONO_OFICINA,' --NO TEL--') || ' Ext.' || EXT
	TELEFONO_OFICINA || ' Ext.' || EXT,' ** SIN TEL**'
    ) AS TELEFONO
	FROM EMPLOYEE
	ORDER BY EMPLOYEE_ID

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME, TELEFONO_OFICINA,EXT
FROM EMPLOYEE
ORDER BY EMPLOYEE_ID

UPDATE EMPLOYEE SET EXT = '123' WHERE EMPLOYEE_ID=1
SELECT COALESCE(NULL,AVG(1))


select
	COALESCE(TELEFONO_OFICINA,' --S/Telef.--') as Campo,
	COALESCE(TELEFONO_OFICINA || ' Ext.' || EXT,' ** SIN TEL**') as Expresion,
	COALESCE(TELEFONO_OFICINA,' --S/Telef.--') || ' Ext.' || Ext as Campo2
	from EMPLOYEE
	order by 1